baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Aristotle Experiment'

[params]
  [params.header]
    title = "Aristotle Experiment"
    subtitle = "Listening to an album a day, from 1/27 to 2/19."
    custom_html = '<script defer src="/script.js" data-website-id="TODO" data-host-url="https://umami.micahbird.com" ></script>'

  [params.footer]
    text = "Made with ❤️ [Hugo](https://gohugo.io/)"

  [params.tier_colors]
    s = "#ff7f7f"
    a = "#ffbf7f"
    b = "#ffdf7f"
    c = "#ffff7f"
    d = "#bfff7f"
    e = "#7fff7f"
    f = "#7fffff"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'All Albums'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
